name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Debug - List Files
        shell: bash
        run: |
          echo "Listing files in ${{ github.workspace }}"
          ls -lR ${{ github.workspace }}

      - name: Debug - Environment Variables
        if: runner.os == 'Linux'
        shell: bash
        run: |
          echo "Environment variables:"
          env
      - name: Debug - Environment Variables
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          echo "Environment variables:"
          Get-ChildItem Env:

      - name: Configure CMake (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          set -x
          SOURCE_DIR="${{ github.workspace }}/lab05dz/lab05dz/banking" # Corrected path
          BUILD_DIR="${{ github.workspace }}/build"
          echo "Source directory: $SOURCE_DIR"
          echo "Build directory: $BUILD_DIR"
          cmake -S "$SOURCE_DIR" -B "$BUILD_DIR" -DCMAKE_BUILD_TYPE=Release
          set +x
      - name: Configure CMake (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $SOURCE_DIR = "${{ github.workspace }}/lab05dz/lab05dz/banking" # Corrected path
          $BUILD_DIR = "${{ github.workspace }}/build"
          Write-Host "Source directory: $SOURCE_DIR"
          Write-Host "Build directory: $BUILD_DIR"
          cmake -S "$SOURCE_DIR" -B "$BUILD_DIR" -DCMAKE_BUILD_TYPE=Release


      - name: Build (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          set -x
          BUILD_DIR="${{ github.workspace }}/build"
          cmake --build "$BUILD_DIR" --config Release
          set +x
      - name: Build (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $BUILD_DIR = "${{ github.workspace }}/build"
          cmake --build "$BUILD_DIR" --config Release
