name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Debug - List Files
        shell: bash
        run: |
          echo "Listing files in ${{ github.workspace }}"
          ls -lR ${{ github.workspace }}

      - name: Debug - Environment Variables
        shell: bash
        run: |
          echo "Environment variables:"
          env

      - name: Configure CMake
        shell: bash
        run: |
          set -x  # Enable command tracing
          SOURCE_DIR="${{ github.workspace }}/your_project_directory" # replace with your directory
          BUILD_DIR="${{ github.workspace }}/build"
          echo "Source directory: $SOURCE_DIR"
          echo "Build directory: $BUILD_DIR"
          cmake -S "$SOURCE_DIR" -B "$BUILD_DIR" -DCMAKE_BUILD_TYPE=Release
          set +x  # Disable command tracing

      - name: Build
        shell: bash
        run: |
          set -x
          BUILD_DIR="${{ github.workspace }}/build"
          cmake --build "$BUILD_DIR" --config Release
          set +x
