name: Build Kali-Hunter DEB Package

on:
  push:
    paths:
      - 'lab07dz/kali-hunter-package/**'
      - '.github/workflows/build.yml'
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: kalilinux/kali-rolling

    steps:
    - uses: actions/checkout@v4

    - name: Build dependencies
      run: |
        apt-get update
        apt-get install -y devscripts debhelper

    - name: Build package
      working-directory: ./lab07dz/kali-hunter-package
      run: |
        dpkg-buildpackage -uc -us
        mv ../kali-hunter_*.* ../
