name: Build and Release Hexline Package

on:
  push:
    branches: ["main"]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: kalilinux/kali-rolling

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: "lab07dz"
        fetch-depth: 0

    - name: Debug structure
      run: |
        echo "Working directory: $(pwd)"
        echo "Contents:"
        ls -R
      working-directory: lab07dz

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y devscripts debhelper equivs

    - name: Build package
      run: |
        cd built-hexline_package
        mk-build-deps --install --remove
        dpkg-buildpackage -uc -us
        mv ../built-hexline_*.* ../
      working-directory: lab07dz

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          lab07dz/built-hexline_*.deb
          lab07dz/built-hexline_*.buildinfo
          lab07dz/built-hexline_*.changes
        tag_name: ${{ github.ref }}
        release_name: "Hexline ${{ github.ref_name }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
