name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B build -DBUILD_TESTING=ON

    - name: Build
      run: cmake --build build

    - name: Test
      run: ctest --test-dir build
