name: CMake Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential

    - name: Configure (root project)
      run: |
        mkdir -p _build
        cmake -B _build -S .

    - name: Build (root project)
      run: |
        cmake --build _build --target all

    - name: Test (subproject)
      working-directory: ./_build
      run: |
        ctest --output-on-failure

    - name: Package
      working-directory: ./_build
      run: |
        cpack -G "TGZ"
        mkdir -p ../artifacts
        mv *.tar.gz ../artifacts/

    - uses: actions/upload-artifact@v3
      with:
        name: packages
        path: artifacts/*.tar.gz
