name: Build and Package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'  # если у вас есть submodules

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential

    - name: Configure CMake
      run: cmake -H. -B_build

    - name: Build project
      run: cmake --build _build

    - name: Create package (TGZ)
      run: |
        cd _build
        cpack -G "TGZ"
        cd ..
        mkdir -p artifacts
        mv _build/*.tar.gz artifacts/

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release-package
        path: artifacts/*.tar.gz
