version: '{build}'
platform: x64
configuration: Release

build: off

build_script:
  - echo "Starting build..."
  - g++ main.cpp -o hello
  - echo "Build complete!"

test_script:
  - echo "Running the program..."
  - ./hello > output.txt # Перенаправляем вывод программы в output.txt
  - echo "Program output:"
  - cat output.txt      # Выводим содержимое output.txt в консоль (Linux/macOS)
  # - type output.txt    # Раскомментируйте эту строку для Windows, а закомментируйте строку выше
  - echo "Tests complete!"
