version: '{branch}.{build}'
image: Visual Studio 2019 # Specifies the build environment

build: off # Отключаем встроенную MSBuild сборку - КЛЮЧЕВОЙ ШАГ

environment:
  matrix:
    - CMAKE_GENERATOR: "Visual Studio 16 2019"  # Или "Visual Studio 17 2022"
      CMAKE_BUILD_TYPE: "Release"

before_build:
  - echo "Configuring CMake..."
  - cmake -H. -Bbuild -G "%CMAKE_GENERATOR%" -DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE%

build_script:
  - echo "Building..."
  - cmake --build build --config %CMAKE_BUILD_TYPE%

test_script: # Use test_script instead of test: off if you have tests.  Otherwise, remove this section.
  - echo "Running tests..."
  - # Замените на команды запуска тестов (например, ctest)

after_build:
  - echo "Build completed!"

artifacts:
  - path: build\Release\*.*
    name: ReleaseBuild

notifications:
  - provider: Email
    to: ilazayzev@gmail.com
    on_build_success: true
    on_build_failure: true
