version: '{build}'
platform: x64

build_script:
  - echo "Starting build..."
  - g++ main.cpp -o hello
  - echo "Build complete!"

test_script:
  - echo "Running the program..."
  - ./hello > output.txt
  - echo "Program output:"
  - cat output.txt
  - echo "Tests complete!"
