version: '{build}'
platform: x64
configuration: Release

build: off

build_script:
  - echo "Starting build..."
  - g++ main.cpp -o hello
  - echo "Build complete!"

test_script:
  - echo "Running the program..."
  - ./hello > output.txt
  - echo "Checking if output.txt exists:"
  - ls -l output.txt
  - echo "Tests complete!"

artifacts:
  - path: output.txt
