version: 1.0.{build}

image: Visual Studio 2019

build: false # Отключаем автоматический режим сборки MSBuild

build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release ..
  - cmd: cmake --build . --config Release --target ALL_BUILD
  - cmd: ctest -C Release .
