name: CMake Hunter Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Необходимо для корректной работы Hunter

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          git \
          libssl-dev

    - name: Clean previous builds
      run: |
        rm -rf ~/.hunter
        rm -rf build

    - name: Configure CMake
      run: |
        cmake -B build \
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
          -DHUNTER_ENABLED=ON

    - name: Build project
      run: |
        cmake --build build \
          --config ${{ env.BUILD_TYPE }} \
          --parallel 2

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure

    - name: Verify installation
      run: |
        cd build
        cmake --install . --prefix install
        ls -R install
