name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Важно для работы Hunter

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          git \
          libssl-dev

    - name: Configure CMake
      run: |
        cmake -B build \
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
          -DHUNTER_ROOT="$HOME/.hunter" \
          -DHUNTER_ENABLED=ON

    - name: Build
      run: cmake --build build --config ${{ env.BUILD_TYPE }} --parallel 2

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure

    - name: Verify installation
      run: |
        cd build
        cmake --install . --prefix install
        ls -R install
