name: CI Pipeline

on:
  push:
    tags: ['v*.*.*']  # Триггер на теги вида v1.0.0
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get version
      id: get_version
      run: |
        VERSION=$(git describe --tags --abbrev=0 | sed 's/^v//')
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "release_name=v${VERSION}" >> $GITHUB_OUTPUT

    - name: Configure
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release \
          -DPROJECT_VERSION=${{ steps.get_version.outputs.version }}

    - name: Build
      run: cmake --build build --config Release

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.release_name }}
        release_name: Release ${{ steps.get_version.outputs.release_name }}
        body: "Version ${{ steps.get_version.outputs.version }}"
        draft: false
        prerelease: false
