name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Важно для Hunter

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          git \
          libssl-dev

    - name: Configure CMake
      run: |
        cmake -B build \
          -DCMAKE_BUILD_TYPE=Release \
          -DHUNTER_ROOT="$HOME/.hunter" \
          -DHUNTER_ENABLED=ON

    - name: Build
      run: cmake --build build --config Release --parallel 2

    - name: Run tests
      run: ctest --test-dir build --output-on-failure
